### ISSUE TITLE
项目已经停止支持了吗？

### ISSUE THREAD

**Issue by Erick-shi** [karmada-io/multi-cluster-ingress-nginx#18]
项目已经停止支持了吗？
我看支持的k8s版本已经很老了

**Comment by XiShanYongYe-Chang** [comment]
This is a demo example to show how to provide multi-cluster ingress capabilities.

We really haven't updated the corresponding version in a while. Would you like to contribute?

**Comment by Erick-shi** [comment]
I'm op,not coder....hei,hei

**Comment by RainbowMango** [comment]
Since this project is developed based on [kubernetes/ingress-nginx](https://github.com/kubernetes/ingress-nginx), we'd better follow the latest base version.
